import assert from "node:assert/strict";
import { Readable } from "node:stream";
import { validateMailPayload, readMailConfig, createMailService, createResendTransport, createMockMailTransport } from "./flickrMail.mjs";
import { createMailHttpHandler } from "./flickrMailServer.mjs";
const env={MAIL_FROM:"sender@example.test",MAIL_REPLY_TO:"feedback@example.test",MAIL_RECIPIENT_ALLOWLIST:"recipient@example.test",MAIL_LIMIT_SECRET:"a".repeat(32),MAIL_API_KEY:"unit-test-only",MAIL_ORIGIN:"http://localhost:5175"};
const config=readMailConfig(env), context={ip:"127.0.0.1",origin:config.origin};
const payload=()=>({requestId:crypto.randomUUID(),sessionId:"session-a",to:"recipient@example.test",subject:"A photo from Flickr",body:"Hello",image:{mediaId:"photo-1",filename:"photo.png",contentType:"image/png",base64:"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jQ0cAAAAASUVORK5CYII="}});
assert.equal(validateMailPayload(payload()).to,"recipient@example.test");
for(const mutate of [p=>p.to="bad",p=>p.to=["a@example.test","b@example.test"],p=>p.to="a@example.test,b@example.test",p=>p.body="x".repeat(4001),p=>p.subject="a\r\nBcc: b@example.test",p=>p.from="spoof@example.test",p=>p.replyTo="spoof@example.test",p=>p.html="<h1>x</h1>",p=>p.image.url="https://remote.test/x.jpg",p=>p.image.base64="a".repeat(8388612),p=>p.image.base64="bm90LXBpY3R1cmU="]) {const p=payload();mutate(p);assert.throws(()=>validateMailPayload(p));}
assert.equal(readMailConfig({}).enabled,false);assert.throws(()=>readMailConfig({...env,MAIL_TRANSPORT:"mock",NODE_ENV:"production"}));
let requests=[];const provider=createResendTransport(config,async(url,options)=>{requests.push({url,options});return new Response(JSON.stringify({id:"test-id"}),{status:200});});
const service=createMailService({config,transport:provider});const p=payload();assert.deepEqual(await service.send(p,context),{accepted:true,mode:"real"});await service.send(p,context);assert.equal(requests.length,1);
const sent=JSON.parse(requests[0].options.body);assert.equal(requests[0].url,"https://api.resend.com/emails");assert.equal(sent.from,"SOCIAL MEDIA, 2010 <sender@example.test>");assert.equal(sent.reply_to,env.MAIL_REPLY_TO);assert.deepEqual(sent.to,[p.to]);assert.equal(sent.attachments[0].content,p.image.base64);assert.ok(!sent.html);assert.equal((sent.text.match(/Sent from SOCIAL MEDIA, 2010/g)||[]).length,1);assert.ok(sent.text.endsWith("If you have feedback, you’re welcome to reply to this email."));
await assert.rejects(service.send({...p,body:"different"},context),e=>e.status===409);
await assert.rejects(service.send(payload(),{...context,origin:"https://other.test"}),e=>e.status===403);
await assert.rejects(service.send({...payload(),to:"outside@example.test"},context),e=>e.status===403);
await service.send(payload(),context);await service.send(payload(),context);await assert.rejects(service.send(payload(),context),e=>e.status===429);
let finish,calls=0;const concurrent=createMailService({config,transport:{sendMemorialEmail:()=>{calls++;return new Promise(resolve=>finish=resolve);}}});const same=payload();const a=concurrent.send(same,context),b=concurrent.send(same,context);await Promise.resolve();assert.equal(calls,1);finish({accepted:true,mode:"real"});await Promise.all([a,b]);
let keys=[],attempts=0;const retry=createMailService({config,transport:{sendMemorialEmail:async(message,key)=>{keys.push(key);if(!attempts++)throw Error("provider error with private data");return {accepted:true,mode:"real"};}}});const retryPayload=payload();await assert.rejects(retry.send(retryPayload,context),e=>e.status===502&&!e.message.includes("private data"));await retry.send(retryPayload,context);assert.equal(keys[0],keys[1]);
const limited=createMailService({config,transport:{sendMemorialEmail:async()=>({accepted:true,mode:"real"})}});for(let i=0;i<6;i++)await limited.send({...payload(),sessionId:`s${i}`},context);await assert.rejects(limited.send({...payload(),sessionId:"new"},context),e=>e.status===429);
const disabled=createMailService({config:readMailConfig({}),transport:{sendMemorialEmail:()=>assert.fail()}});await assert.rejects(disabled.send(payload(),{ip:"ip",origin:"http://127.0.0.1:5175"}),e=>e.status===503);
const mock=createMailService({config:readMailConfig({...env,MAIL_TRANSPORT:"mock"}),transport:createMockMailTransport()});assert.deepEqual(await mock.send(payload(),context),{accepted:false,mode:"mock"});
// Real HTTP boundary tested with streams; no sockets or external delivery.
let peer;const handler=createMailHttpHandler({origin:config.origin,service:{configuration:()=>({enabled:true}),send:async(p,c)=>{peer=c.ip;return {accepted:true,mode:"real"};}}});
async function http(body,headers={},method="POST",url="/api/flickr-mail") {const req=Readable.from([Buffer.from(body)]);Object.assign(req,{url,method,headers:{origin:config.origin,"content-type":"application/json",...headers},socket:{remoteAddress:"socket-ip"}});let status,result;const res={headersSent:false,writeHead(s){status=s;this.headersSent=true;},end(s){result=JSON.parse(s);}};await handler(req,res);return {status,result};}
assert.equal((await http(JSON.stringify(payload()),{"x-forwarded-for":"forged-ip"})).status,200);assert.equal(peer,"socket-ip");assert.equal((await http("bad-json")).status,400);assert.equal((await http("{}",{origin:"https://bad.test"})).status,403);assert.equal((await http("{}",{"content-length":"999999999"})).status,413);assert.equal((await http("{}",{"content-type":"text/plain"})).status,415);
console.log("PASS: server recipient/payload/header/media validation, closed pilot, per-session/IP limits, duplicate/retry idempotency, provider envelope/attachment/footer, redacted failures, mock safeguards and HTTP boundary. No live email sent.");
