import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { createServer } from 'vite';
const server = await createServer({ server:{middlewareMode:true}, appType:'custom', logLevel:'silent' });
const walk = n => !n || typeof n !== 'object' ? [] : Array.isArray(n) ? n.flatMap(walk) : [n,...walk(n.props?.children)];
try {
  const f = await server.ssrLoadModule('/src/state/facebookState.ts');
  const { FacebookContainer } = await server.ssrLoadModule('/src/device/FacebookContainer.tsx');
  const { SessionIdentityContext } = await server.ssrLoadModule('/src/state/sessionIdentity.ts');
  const { IOS4KeyboardSystem } = await server.ssrLoadModule('/src/device/IOS4KeyboardSystem.tsx');
  let state = {...f.createInitialFacebookState('Visitor'),currentView:'placeTagFriends'};
  const dispatch = event => state = f.facebookStateTransition(state,event);
  const render = () => renderToStaticMarkup(createElement(SessionIdentityContext.Provider,{value:{name:'Visitor'}},createElement(IOS4KeyboardSystem,{},createElement(FacebookContainer,{state,dispatch,currentDeviceTime:'12:02',elapsedMs:0}))));
  const initial = render();
  assert.ok(initial.includes('type="checkbox"'));
  assert.ok(!initial.includes('checked=""'));
  const friendId = state.friends[0].id;
  dispatch({type:'TOGGLE_PLACE_TAGGED_FRIEND',friendId});
  assert.deepEqual(state.placeTaggedFriendIds,[friendId]);
  assert.match(render(),/<input[^>]*type="checkbox"[^>]*checked=""/);
  dispatch({type:'TOGGLE_PLACE_TAGGED_FRIEND',friendId});
  assert.deepEqual(state.placeTaggedFriendIds,[]);
  assert.equal(render(),initial,'toggle round trip preserves native label/control markup');
  const css = readFileSync(new URL('../styles/device.css',import.meta.url),'utf8');
  assert.match(css,/\.facebook-place-tag-friends input\[type="checkbox"\] \{[^}]*appearance:none;[^}]*width:15px; height:15px/);
  assert.match(css,/\.facebook-place-tag-friends input\[type="checkbox"\]:checked \{[^}]*background-image:/);
  assert.match(css,/\.facebook-place-tag-friends input\[type="checkbox"\]:focus-visible \{[^}]*outline:1px solid/);
  const mailCss = readFileSync(new URL('../styles/flickrMail.css',import.meta.url),'utf8');
  assert.match(mailCss,/\.flickr-mail-row input:focus,\s*\.flickr-mail-message textarea:focus \{ outline:none; box-shadow:inset 0 -1px 0 #6d85a5; \}/);
  const { NotesContainer } = await server.ssrLoadModule('/src/device/SmallApps.tsx');
  const m = await server.ssrLoadModule('/src/state/smallApps.ts');
  let notes = m.initialSmallApps();
  const send = e => notes = m.smallAppsTransition(notes,e);
  send({type:'CREATE'}); const id=notes.selected;
  const text='A very long first line '.repeat(40)+'\nSecond line preserved';
  send({type:'EDIT',id,text});send({type:'LIST'});
  const nodes=walk(NotesContainer({state:notes,dispatch:send}));
  assert.equal(nodes.find(n=>n.props?.className==='small-note-title').props.children,text.split('\n')[0]);
  assert.equal(nodes.find(n=>n.props?.className==='small-note-chevron').props.children,'›');
  nodes.find(n=>n.type==='button' && walk(n).some(c=>c.props?.className==='small-note-title')).props.onClick();
  assert.equal(notes.selected,id);assert.equal(notes.notes[0].text,text,'ellipsis never truncates stored content');
  const notesCss=readFileSync(new URL('../styles/smallApps.css',import.meta.url),'utf8');
  assert.match(notesCss,/\.small-note-title \{ flex:1 1 auto; min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;/);
  assert.match(notesCss,/\.small-note-chevron \{ flex:0 0 12px;/);
  console.log('PASS: native checkbox selection/labels, scoped focus styles, long Notes title/open/content preservation and fixed chevron contract');
} finally { await server.close(); }
