import { LoadingIndicator } from "./FinalDecorativeApps";
import { useRef, type Dispatch } from "react";
import { cardinalHeading, durationText, stopwatchElapsed, timerRemaining, type ClockTab, type RemainingBasicAppsState, type RemainingBasicAppsEvent } from "../state/remainingBasicApps";
import type { useVoiceMemos } from "./useVoiceMemos";
import whatsAppIcon from "../assets/historical/ios4.1/springboard/apps/WhatsApp-2010-AppStore.jpg";
import skypeIcon from "../assets/historical/ios4.1/springboard/apps/Skype-2010-AppStore.jpg";
import "../styles/remainingBasicApps.css";
export type RemainingAppsProps={state:RemainingBasicAppsState;dispatch:Dispatch<RemainingBasicAppsEvent>};
const tabs:ClockTab[]=["World Clock","Alarm","Stopwatch","Timer"];
const two=(n:number)=>String(n).padStart(2,"0");
export function ClockContainer({state:s,dispatch,now,worldTime}:RemainingAppsProps & {now:number;worldTime:string}) {
 const left=timerRemaining(s.timer,now),done=s.timer.startedAt!==null && left===0;
 return <section className="remaining-clock" aria-label="Clock"><header className="remaining-nav"><strong>{s.tab}</strong></header><main>
 {s.tab==="World Clock" && <div className="world-clock-row"><strong>Los Angeles</strong><time>{worldTime}</time></div>}
 {s.tab==="Alarm" && <section className="alarm-surface">{s.alarmEditing ? <><h2>Add Alarm</h2><div className="time-picker">{(["HOUR","MINUTE"] as const).map((unit,i)=><div key={unit}><button type="button" aria-label={`Increase alarm ${unit.toLowerCase()}`} onClick={()=>dispatch({type:`ALARM_${unit}`,delta:1})}>▲</button><output>{two(i===0?s.alarmHour:s.alarmMinute)}</output><button type="button" aria-label={`Decrease alarm ${unit.toLowerCase()}`} onClick={()=>dispatch({type:`ALARM_${unit}`,delta:-1})}>▼</button><small>{i===0?"hours":"minutes"}</small></div>)}</div><button type="button" onClick={()=>dispatch({type:"ALARM_CANCEL"})}>Cancel</button><button type="button" onClick={()=>dispatch({type:"ALARM_SAVE"})}>Save</button></> : <><button type="button" onClick={()=>dispatch({type:"ALARM_EDIT"})}>{s.alarm?"Edit":"Add"}</button>{s.alarm && <div className="alarm-row"><strong>{two(s.alarm.hour)}:{two(s.alarm.minute)}</strong><button type="button" role="switch" aria-checked={s.alarm.enabled} onClick={()=>dispatch({type:"ALARM_TOGGLE"})}>{s.alarm.enabled?"ON":"OFF"}</button><button type="button" onClick={()=>dispatch({type:"ALARM_DELETE"})}>Delete</button></div>}</>}</section>}
 {s.tab==="Stopwatch" && <section className="clock-counter"><output>{durationText(stopwatchElapsed(s.stopwatch,now))}</output><div><button type="button" className={s.stopwatch.startedAt===null?"start":"stop"} onClick={()=>dispatch({type:s.stopwatch.startedAt===null?"STOPWATCH_START":"STOPWATCH_STOP",now:performance.now()})}>{s.stopwatch.startedAt===null?"Start":"Stop"}</button><button type="button" disabled={s.stopwatch.startedAt!==null} onClick={()=>dispatch({type:"STOPWATCH_RESET"})}>Reset</button></div></section>}
 {s.tab==="Timer" && <section className="clock-counter">{s.timer.startedAt===null && <div className="time-picker">{[["hours",3600000],["minutes",60000],["seconds",1000]].map(([label,step])=><div key={label}><button type="button" aria-label={`Increase timer ${label}`} onClick={()=>dispatch({type:"TIMER_DURATION",duration:s.timer.duration+Number(step)})}>▲</button><small>{label}</small><button type="button" aria-label={`Decrease timer ${label}`} onClick={()=>dispatch({type:"TIMER_DURATION",duration:s.timer.duration-Number(step)})}>▼</button></div>)}</div>}<output>{durationText(left)}</output>{done && <p role="status">Timer Done</p>}<div><button type="button" className="start" onClick={()=>dispatch({type:s.timer.startedAt===null || done?"TIMER_START":"TIMER_PAUSE",now:performance.now()})}>{s.timer.startedAt===null || done?"Start":"Pause"}</button><button type="button" onClick={()=>dispatch({type:"TIMER_CANCEL"})}>Cancel</button></div></section>}
 </main><nav className="remaining-tabs" aria-label="Clock tabs">{tabs.map(tab=><button type="button" key={tab} aria-current={s.tab===tab?"page":undefined} onClick={()=>dispatch({type:"CLOCK_TAB",tab})}>{tab}</button>)}</nav></section>;
}
export function CompassContainer({state,dispatch}:RemainingAppsProps) {
 const drag=useRef<{x:number;heading:number;id:number}|null>(null);
 return <section className="remaining-compass" aria-label="Compass"><div className="compass-readout"><strong>{Math.round(state.heading)%360}° {cardinalHeading(state.heading)}</strong><small>Simulated heading</small></div><div className="compass-drag" aria-label="Drag horizontally to change heading" onPointerDown={e=>{if(!e.isPrimary || e.button!==0)return;drag.current={x:e.clientX,heading:state.heading,id:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current?.id===e.pointerId)dispatch({type:"HEADING",heading:drag.current.heading+e.clientX-drag.current.x});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onLostPointerCapture={()=>{drag.current=null;}}><svg viewBox="0 0 300 300" role="img" aria-label="Compass dial"><circle cx="150" cy="150" r="140" fill="#111" stroke="#888" strokeWidth="5"/><g transform={`rotate(${-state.heading} 150 150)`}>{Array.from({length:72},(_,i)=><line key={i} x1="150" y1="17" x2="150" y2={i%6===0?32:24} stroke="#ddd" strokeWidth={i%6===0?2:1} transform={`rotate(${i*5} 150 150)`}/>)}{["N","E","S","W"].map((label,i)=><text key={label} x="150" y="56" textAnchor="middle" fill={i===0?"#c94942":"#eee"} fontSize="25" transform={`rotate(${i*90} 150 150)`}>{label}</text>)}<path d="M150 68L140 150H160Z" fill="#b53c35"/><path d="M150 232L140 150H160Z" fill="#ddd"/></g><circle cx="150" cy="150" r="7" fill="#999"/><path d="M145 4L150 15L155 4" fill="#eee"/></svg></div></section>;
}
export function VoiceMemosContainer({memos,now}:{memos:ReturnType<typeof useVoiceMemos>;now:number}) {
 const {state:s,controller:c}=memos,busy=s.phase==="requesting" || s.phase==="stopping";
 return <section className="remaining-voice" aria-label="Voice Memos"><header className="remaining-nav"><strong>Voice Memos</strong></header><div className="memo-instrument"><svg viewBox="0 0 180 170" aria-hidden="true"><defs><linearGradient id="memo-metal"><stop stopColor="#555"/><stop offset=".5" stopColor="#ddd"/><stop offset="1" stopColor="#555"/></linearGradient></defs><rect x="60" y="12" width="60" height="100" rx="28" fill="url(#memo-metal)" stroke="#222" strokeWidth="3"/>{Array.from({length:9},(_,i)=><path key={i} d={`M69 ${27+i*8}H111`} stroke="#333" strokeWidth="3"/>)}<path d="M48 75V93Q48 126 90 126Q132 126 132 93V75M90 127V152M63 154H117" fill="none" stroke="#aaa" strokeWidth="7"/></svg><output>{durationText(s.startedAt===null?0:now-s.startedAt)}</output>{s.phase==="failed" && <p role="status">Recording unavailable.</p>}{s.phase==="recording" && s.simulated && <p role="status">Simulated recording — no audio</p>}<div><button type="button" disabled={busy} className="memo-record" onClick={()=>s.phase==="recording"?c.stop():void c.record()}>{s.phase==="recording"?"Stop":s.phase==="requesting"?"Please wait…":s.phase==="stopping"?"Saving…":"Record"}</button>{s.phase==="failed" && <button type="button" onClick={()=>void c.record(true)}>Record simulation</button>}</div></div><ol className="memo-list" aria-label="Recordings">{s.recordings.map(m=><li key={m.id}><span><strong>Memo {m.id}</strong><small>{durationText(m.duration)}{m.simulated?" · Simulated — no audio":""}</small></span>{m.url && <button type="button" disabled={s.phase!=="idle" && s.phase!=="failed"} onClick={()=>void c.play(m.id)}>{s.playingId===m.id?"Stop":"Play"}</button>}</li>)}</ol></section>;
}
export function LegacyLoadingContainer({appId}:{appId:"whatsapp"|"skype"}) {
 if(appId === "whatsapp") return <section className="remaining-loading whatsapp-loading" aria-label="WhatsApp" data-presentation="RECONSTRUCTED"><img className="whatsapp-loading-mark" src={whatsAppIcon} alt="WhatsApp"/><div className="whatsapp-loading-progress"><LoadingIndicator /></div></section>;
 return <section className="remaining-loading skype-loading" aria-label="Skype" data-presentation="RECONSTRUCTED"><div className="skype-loading-brand"><img src={skypeIcon} alt="Skype"/></div><div className="skype-loading-progress"><LoadingIndicator /></div></section>;
}
