import assert from "node:assert/strict";
import { createServer } from "vite";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
const server = await createServer({ server: { middlewareMode: true }, appType: "custom", logLevel: "silent" });
try {
  const { createInitialFlickrState: initial, flickrStateTransition: reduce, selectFlickrPhotos: photos } = await server.ssrLoadModule("/src/state/flickrState.ts");
  const { FLICKR_PHOTOS } = await server.ssrLoadModule("/src/data/flickrContent.ts");
  const { SHARED_CHARACTER_MEDIA } = await server.ssrLoadModule("/src/data/sharedCharacterMedia.ts");
  const { simulatedDeviceDateTime } = await server.ssrLoadModule("/src/state/deviceMachine.ts");
  const { FlickrContainer } = await server.ssrLoadModule("/src/device/FlickrContainer.tsx");
  const { IOS4KeyboardSystem } = await server.ssrLoadModule("/src/device/IOS4KeyboardSystem.tsx");
  const { SessionIdentityContext } = await server.ssrLoadModule("/src/state/sessionIdentity.ts");
  let state = initial();
  const send = e => state = reduce(state,e);
  const markup = () => renderToStaticMarkup(createElement(SessionIdentityContext.Provider,{value:{name:"Visitor"}},createElement(IOS4KeyboardSystem,{},createElement(FlickrContainer,{state,dispatch:send}))));
  assert.equal(state.currentView,"home");assert.match(markup(),/flickr-home-buttons/);
  assert.equal(FLICKR_PHOTOS.length,5);
  for(const photo of state.photos) {
    const shared=SHARED_CHARACTER_MEDIA[photo.mediaId];
    assert.equal(photo.src,shared.src);assert.equal(photo.ownerId,shared.canonicalCharacterId);assert.equal(photo.uploadedAt,shared.timestamp);
    assert.ok(Date.parse(photo.uploadedAt)<simulatedDeviceDateTime(0).getTime());
  }
  for(const view of ["contacts","recent","activity"]) {send({type:"NAVIGATE",view});assert.ok(markup().includes('aria-label="Flickr"'));}
  send({type:"SHOW_PHOTOSTREAM"});assert.equal(photos(state).length,0);assert.match(markup(),/No photos/);
  send({type:"SHOW_PHOTOSTREAM",ownerId:"jay"});assert.equal(photos(state).length,3);
  const first=photos(state)[0];
  send({type:"OPEN_PHOTO",photoId:first.id,origin:{view:"photostream"},photostreamScrollPosition:80});
  assert.match(markup(),/by Jay/);assert.doesNotMatch(markup(),/by Visitor/);
  const footer = markup().match(/<div class="flickr-toolbar"[^]*?<\/div>/)?.[0];
  assert.ok(footer);
  assert.deepEqual([...footer.matchAll(/<button[^>]*aria-label="([^"]+)"/g)].map(m=>m[1]),["Email photo","Previous photo","Next photo","Comment"]);
  assert.equal((footer.match(/<svg /g)??[]).length,4,"footer glyphs must be deterministic assets");
  assert.match(footer,/<button disabled="" aria-label="Email photo"/);
  assert.match(footer,/<button aria-label="Previous photo" disabled=""/);
  assert.doesNotMatch(footer,/Play|Slideshow|Share|Twitter|Facebook|Tumblr|Copy Link|↗|◀|▶|▱/);
  // Preserve the exact footer callback mapping, including Next rather than Play.
  const { readFile } = await import("node:fs/promises");
  const containerSource = await readFile(new URL("../device/FlickrContainer.tsx",import.meta.url),"utf8");
  const footerStart = containerSource.indexOf('<div className="flickr-toolbar"');
  const footerSource = containerSource.slice(footerStart,containerSource.indexOf('{view === "fullscreen"',footerStart));
  assert.match(footerSource,/aria-label="Previous photo"[^]*?STEP_PHOTO", direction: -1/);
  assert.match(footerSource,/aria-label="Next photo"[^]*?STEP_PHOTO", direction: 1/);
  assert.match(footerSource,/aria-label="Comment"[^]*?COMPOSE_COMMENT/);
  send({type:"STEP_PHOTO",direction:1});send({type:"STEP_PHOTO",direction:1});
  assert.match(markup(),/<button aria-label="Next photo" disabled=""/);
  send({type:"STEP_PHOTO",direction:-1});send({type:"STEP_PHOTO",direction:-1});
  send({type:"FULLSCREEN"});assert.equal(state.currentView,"fullscreen");assert.match(markup(),/flickr-fullscreen/);
  send({type:"STEP_PHOTO",direction:1});assert.notEqual(state.selectedPhotoId,first.id);assert.equal(state.fullscreenControls,false);
  send({type:"BACK_TO_PHOTO"});send({type:"BACK_FROM_PHOTO"});assert.equal(state.currentView,"photostream");assert.equal(state.photostreamScrollPosition,80);
  send({type:"SHOW_SETS"});assert.match(markup(),/Music/);send({type:"OPEN_SET",setId:"jay-music"});assert.equal(photos(state).length,3);
  send({type:"OPEN_PHOTO",photoId:first.id,origin:{view:"set",setId:"jay-music"}});send({type:"BACK_FROM_PHOTO"});assert.equal(state.currentView,"set");
  send({type:"NAVIGATE",view:"tags"});assert.match(markup(),/music/);send({type:"OPEN_TAG",tag:"music"});assert.equal(photos(state).length,3);
  send({type:"NAVIGATE",view:"search"});send({type:"SEARCH_QUERY",value:"guitar"});send({type:"SEARCH"});assert.equal(photos(state).length,2);assert.deepEqual(state.recentSearches,["guitar"]);
  send({type:"SEARCH_SCOPE",scope:"own"});assert.equal(photos(state).length,0);send({type:"SEARCH_SCOPE",scope:"contacts"});assert.equal(photos(state).length,2);
  send({type:"CLEAR_SEARCHES"});assert.deepEqual(state.recentSearches,[]);assert.equal(state.searchQuery,"");
  send({type:"OPEN_PHOTO",photoId:first.id,origin:{view:"recent"}});send({type:"COMPOSE_COMMENT"});send({type:"EDIT_COMMENT",value:"Hello"});assert.match(markup(),/flickr-comment-/);
  send({type:"SUBMIT_COMMENT",author:"Visitor"});send({type:"SUBMIT_COMMENT",author:"Visitor"});assert.equal(state.commentsState.length,1);
  send({type:"TOGGLE_FAVORITE",photoId:first.id});send({type:"SHOW_PHOTOSTREAM"});send({type:"NAVIGATE",view:"favorites"});assert.equal(photos(state).length,1);
  send({type:"TOGGLE_FAVORITE",photoId:first.id});assert.equal(photos(state).length,0);
  const attachment={id:"camera-1",objectUrl:"blob:camera-1",filename:"IMG_0001.JPG"};
  send({type:"MEDIA_RETURN",attachment,takenAt:simulatedDeviceDateTime(1000).toISOString()});
  const pending=state.pendingUpload;send({type:"MEDIA_RETURN"});assert.strictEqual(state.pendingUpload,pending);
  send({type:"EDIT_UPLOAD",field:"description",value:"description"});send({type:"EDIT_UPLOAD",field:"tags",value:"music music,home"});send({type:"TOGGLE_LOCATION"});
  const before=state.photos.length;
  send({type:"BEGIN_UPLOAD",experienceSessionId:"a",elapsedMs:2000,author:"Visitor"});
  const job=state.upload;assert.ok(job);send({type:"BEGIN_UPLOAD",experienceSessionId:"a",elapsedMs:2000,author:"Visitor"});assert.strictEqual(state.upload,job);
  send({type:"ADVANCE_UPLOAD",experienceSessionId:"b",elapsedMs:10000});assert.equal(state.photos.length,before);
  send({type:"ADVANCE_UPLOAD",experienceSessionId:"a",elapsedMs:4999});assert.equal(state.photos.length,before);
  send({type:"ADVANCE_UPLOAD",experienceSessionId:"a",elapsedMs:5000});send({type:"ADVANCE_UPLOAD",experienceSessionId:"a",elapsedMs:8000});
  assert.equal(state.photos.length,before+1);assert.equal(state.photos[0].mediaId,attachment.id);assert.equal(state.photos[0].src,attachment.objectUrl);
  assert.equal(state.photos[0].uploadedAt,"2010-10-20T07:02:05.000Z");assert.equal(state.photos[0].takenAt,"2010-10-20T07:02:01.000Z");assert.deepEqual(state.photos[0].tags,["music","home"]);
  assert.deepEqual(state.photos[0].location,{xMiles:0,yMiles:0});assert.equal(state.photos[0].privacy,"private");
  send({type:"SHOW_PHOTOSTREAM"});assert.equal(photos(state).length,1);assert.equal(state.upload,null);
  send({type:"MEDIA_RETURN",attachment,takenAt:simulatedDeviceDateTime(1000).toISOString()});send({type:"BEGIN_UPLOAD",experienceSessionId:"a",elapsedMs:899999,author:"Visitor"});assert.equal(state.upload,null);
  send({type:"BEGIN_UPLOAD",experienceSessionId:"a",elapsedMs:10000,author:"Visitor"});assert.ok(state.upload);
  send({type:"RESET"});send({type:"ADVANCE_UPLOAD",experienceSessionId:"a",elapsedMs:20000});assert.deepEqual(state,initial());
  assert.equal(FLICKR_PHOTOS.length,5);assert.equal(FLICKR_PHOTOS.some(p=>p.origin!=="seed"),false);
  console.log("PASS: Flickr canonical assets, browsing/SSR, scopes/recent-clear, fullscreen/order, sets/tags, comments/favorites, draft/cancel, idempotent publication, timing/location, terminal guard and stale-session reset.");
} finally { await server.close(); }
